/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mockups;

import javax.swing.JFrame;
import robogp.matchmanager.RobotMarker;
import robogp.robodrome.Direction;
import robogp.robodrome.Robodrome;
import robogp.robodrome.Rotation;
import robogp.robodrome.view.RobodromeView;

/**
 *
 * @author claudia
 */
public class GameTestFrame extends javax.swing.JFrame {

    private final RobodromeView rv;
    private RobotMarker[] robots;

    /**
     * Creates new form GameTestFrame
     */
    public GameTestFrame() {
        initComponents();
        rv = new RobodromeView(new Robodrome("./robodromes/riskyexchange.txt"), 55);
        splitPane.setRightComponent(rv);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        setup1Button = new javax.swing.JButton();
        loadRegButton = new javax.swing.JButton();
        exeRegButton = new javax.swing.JButton();
        exeBoardButton = new javax.swing.JButton();
        shootButton = new javax.swing.JButton();
        loadReg2Button = new javax.swing.JButton();
        exeReg2Button = new javax.swing.JButton();
        exeBoard2Button = new javax.swing.JButton();
        shoot2Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        redPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        redCardPanel = new javax.swing.JPanel();
        redPriorityLabel = new javax.swing.JLabel();
        redCardLabel = new javax.swing.JLabel();
        redCardNameLabel = new javax.swing.JLabel();
        bluePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        blueCardPanel = new javax.swing.JPanel();
        bluePriorityLabel = new javax.swing.JLabel();
        blueCardLabel = new javax.swing.JLabel();
        blueCardNameLabel = new javax.swing.JLabel();
        yellowPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        yellowCardPanel = new javax.swing.JPanel();
        yellowPriorityLabel = new javax.swing.JLabel();
        yellowCardLabel = new javax.swing.JLabel();
        yellowCardNameLabel = new javax.swing.JLabel();
        emeraldPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        emeraldCardPanel = new javax.swing.JPanel();
        emeraldPriorityLabel = new javax.swing.JLabel();
        emeraldCardLabel = new javax.swing.JLabel();
        emeraldCardNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        splitPane.setDividerLocation(100);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        setup1Button.setText("Setup");
        setup1Button.setAlignmentX(0.5F);
        setup1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setup1ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(setup1Button);

        loadRegButton.setText("load REG");
        loadRegButton.setAlignmentX(0.5F);
        loadRegButton.setEnabled(false);
        loadRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRegButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loadRegButton);

        exeRegButton.setText("exe REG");
        exeRegButton.setAlignmentX(0.5F);
        exeRegButton.setEnabled(false);
        exeRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeRegButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exeRegButton);

        exeBoardButton.setText("exe BOARD");
        exeBoardButton.setAlignmentX(0.5F);
        exeBoardButton.setEnabled(false);
        exeBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeBoardButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exeBoardButton);

        shootButton.setText("SHOOT");
        shootButton.setAlignmentX(0.5F);
        shootButton.setEnabled(false);
        shootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootButtonActionPerformed(evt);
            }
        });
        jPanel1.add(shootButton);

        loadReg2Button.setText("load REG");
        loadReg2Button.setAlignmentX(0.5F);
        loadReg2Button.setEnabled(false);
        loadReg2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadReg2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loadReg2Button);

        exeReg2Button.setText("exe REG");
        exeReg2Button.setAlignmentX(0.5F);
        exeReg2Button.setEnabled(false);
        exeReg2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeReg2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exeReg2Button);

        exeBoard2Button.setText("exe BOARD");
        exeBoard2Button.setAlignmentX(0.5F);
        exeBoard2Button.setEnabled(false);
        exeBoard2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeBoard2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(exeBoard2Button);

        shoot2Button.setText("SHOOT");
        shoot2Button.setAlignmentX(0.5F);
        shoot2Button.setEnabled(false);
        shoot2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoot2ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(shoot2Button);

        splitPane.setLeftComponent(jPanel1);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        jPanel2.setMaximumSize(new java.awt.Dimension(150, 32767));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 1000));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        redPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        redPanel.setAlignmentX(0.0F);
        redPanel.setAlignmentY(0.0F);
        redPanel.setLayout(new javax.swing.BoxLayout(redPanel, javax.swing.BoxLayout.X_AXIS));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/robot-red.png"))); // NOI18N
        redPanel.add(jLabel1);

        redCardPanel.setLayout(new javax.swing.BoxLayout(redCardPanel, javax.swing.BoxLayout.Y_AXIS));

        redPriorityLabel.setAlignmentX(0.5F);
        redCardPanel.add(redPriorityLabel);

        redCardLabel.setAlignmentX(0.5F);
        redCardLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        redCardLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        redCardLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        redCardPanel.add(redCardLabel);

        redCardNameLabel.setAlignmentX(0.5F);
        redCardPanel.add(redCardNameLabel);

        redPanel.add(redCardPanel);

        jPanel2.add(redPanel);

        bluePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        bluePanel.setAlignmentX(0.0F);
        bluePanel.setAlignmentY(0.0F);
        bluePanel.setLayout(new javax.swing.BoxLayout(bluePanel, javax.swing.BoxLayout.X_AXIS));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/robot-blue.png"))); // NOI18N
        bluePanel.add(jLabel2);

        blueCardPanel.setLayout(new javax.swing.BoxLayout(blueCardPanel, javax.swing.BoxLayout.Y_AXIS));

        bluePriorityLabel.setAlignmentX(0.5F);
        blueCardPanel.add(bluePriorityLabel);

        blueCardLabel.setAlignmentX(0.5F);
        blueCardLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        blueCardLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        blueCardLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        blueCardPanel.add(blueCardLabel);

        blueCardNameLabel.setAlignmentX(0.5F);
        blueCardPanel.add(blueCardNameLabel);

        bluePanel.add(blueCardPanel);

        jPanel2.add(bluePanel);

        yellowPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        yellowPanel.setAlignmentX(0.0F);
        yellowPanel.setAlignmentY(0.0F);
        yellowPanel.setLayout(new javax.swing.BoxLayout(yellowPanel, javax.swing.BoxLayout.X_AXIS));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/robot-yellow.png"))); // NOI18N
        yellowPanel.add(jLabel3);

        yellowCardPanel.setLayout(new javax.swing.BoxLayout(yellowCardPanel, javax.swing.BoxLayout.Y_AXIS));

        yellowPriorityLabel.setAlignmentX(0.5F);
        yellowCardPanel.add(yellowPriorityLabel);

        yellowCardLabel.setAlignmentX(0.5F);
        yellowCardLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        yellowCardLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        yellowCardLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        yellowCardPanel.add(yellowCardLabel);

        yellowCardNameLabel.setAlignmentX(0.5F);
        yellowCardPanel.add(yellowCardNameLabel);

        yellowPanel.add(yellowCardPanel);

        jPanel2.add(yellowPanel);

        emeraldPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        emeraldPanel.setAlignmentX(0.0F);
        emeraldPanel.setAlignmentY(0.0F);
        emeraldPanel.setLayout(new javax.swing.BoxLayout(emeraldPanel, javax.swing.BoxLayout.X_AXIS));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/robot-emerald.png"))); // NOI18N
        emeraldPanel.add(jLabel4);

        emeraldCardPanel.setLayout(new javax.swing.BoxLayout(emeraldCardPanel, javax.swing.BoxLayout.Y_AXIS));

        emeraldPriorityLabel.setAlignmentX(0.5F);
        emeraldCardPanel.add(emeraldPriorityLabel);

        emeraldCardLabel.setAlignmentX(0.5F);
        emeraldCardLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        emeraldCardLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        emeraldCardLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        emeraldCardPanel.add(emeraldCardLabel);

        emeraldCardNameLabel.setAlignmentX(0.5F);
        emeraldCardPanel.add(emeraldCardNameLabel);

        emeraldPanel.add(emeraldCardPanel);

        jPanel2.add(emeraldPanel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        setBounds(0, 0, 800, 622);
    }// </editor-fold>//GEN-END:initComponents

    private void setup1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setup1ButtonActionPerformed

        String[] ROBOT_COLORS = {"red", "blue", "yellow", "emerald", "violet", "orange", "turquoise", "green"};
        String[] ROBOT_NAMES = {"robot-red", "robot-blue", "robot-yellow", "robot-emerald", "robot-violet", "robot-orange", "robot-turquoise", "robot-green"};
        robots = new RobotMarker[ROBOT_NAMES.length];
        for (int i = 0; i < ROBOT_NAMES.length; i++) {
            robots[i] = new RobotMarker(ROBOT_NAMES[i], ROBOT_COLORS[i]);
        }
        rv.placeRobot(robots[0], Direction.E, 5, 0, true);
        rv.placeRobot(robots[1], Direction.E, 6, 0, true);
        rv.placeRobot(robots[2], Direction.E, 3, 1, true);
        rv.placeRobot(robots[3], Direction.E, 8, 1, true);
        this.setup1Button.setEnabled(false);
        this.loadRegButton.setEnabled(true);
    }//GEN-LAST:event_setup1ButtonActionPerformed

    private void loadRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRegButtonActionPerformed
        this.redCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/card-move2.png")));
        this.redCardNameLabel.setText("Move 2");
        this.redPriorityLabel.setText("710");
        this.blueCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/card-move1.png")));
        this.bluePriorityLabel.setText("530");
        this.blueCardNameLabel.setText("Move 1");
        this.yellowCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/card-move3.png")));
        this.yellowCardNameLabel.setText("Move 3");
        this.yellowPriorityLabel.setText("820");
        this.emeraldCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/card-turnR.png")));
        this.emeraldCardNameLabel.setText("Turn R");
        this.emeraldPriorityLabel.setText("240");
        this.repaint();
        this.loadRegButton.setEnabled(false);
        this.exeRegButton.setEnabled(true);
    }//GEN-LAST:event_loadRegButtonActionPerformed

    private void exeRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeRegButtonActionPerformed
        rv.addRobotMove(robots[2], 3, Direction.E, Rotation.NO);
        rv.addRobotMove(robots[0], 2, Direction.E, Rotation.NO);
        rv.addRobotMove(robots[1], 1, Direction.E, Rotation.NO);
        rv.addRobotMove(robots[3], 0, Direction.E, Rotation.CW90);
        rv.play();
        this.exeRegButton.setEnabled(false);
        this.exeBoardButton.setEnabled(true);
    }//GEN-LAST:event_exeRegButtonActionPerformed

    private void exeBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeBoardButtonActionPerformed
        rv.addRobotMove(robots[2], 1, Direction.E, Rotation.NO);
        rv.play();
        this.exeBoardButton.setEnabled(false);
        this.shootButton.setEnabled(true);
    }//GEN-LAST:event_exeBoardButtonActionPerformed

    private void shootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootButtonActionPerformed
        rv.addLaserFire(robots[0], Direction.E, 2, 15, false, false);
        rv.addPause(500);
        rv.addLaserFire(robots[1], Direction.E, 1, 15, false, false);
        rv.addPause(500);
        rv.addLaserFire(robots[2], Direction.E, 5, 15, false, false);
        rv.addPause(500);
        rv.addLaserFire(robots[3], Direction.S, 8, 11, false, false);
        rv.addPause(1000);
        rv.addHideLaser();
        rv.play();
        this.shootButton.setEnabled(false);
        this.loadReg2Button.setEnabled(true);
    }//GEN-LAST:event_shootButtonActionPerformed

    private void loadReg2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadReg2ButtonActionPerformed
        this.redCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/card-move3.png")));
        this.redCardNameLabel.setText("Move 3");
        this.redPriorityLabel.setText("800");
        this.blueCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/card-turnR.png")));
        this.bluePriorityLabel.setText("380");
        this.blueCardNameLabel.setText("Turn R");
        this.yellowCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/card-turnL.png")));
        this.yellowCardNameLabel.setText("Turn L");
        this.yellowPriorityLabel.setText("250");
        this.emeraldCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mockups/icons/card-move2.png")));
        this.emeraldCardNameLabel.setText("Move 2");
        this.emeraldPriorityLabel.setText("690");
        this.repaint();
        this.loadReg2Button.setEnabled(false);
        this.exeReg2Button.setEnabled(true);
    }//GEN-LAST:event_loadReg2ButtonActionPerformed

    private void exeReg2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeReg2ButtonActionPerformed
        rv.addRobotMove(robots[0], 3, Direction.E, Rotation.NO);
        rv.addRobotMove(robots[3], 2, Direction.S, Rotation.NO);
        rv.addRobotMove(robots[1], 0, Direction.E, Rotation.CW90);
        rv.addRobotMove(robots[2], 0, Direction.E, Rotation.CCW90);
        rv.play();
        this.exeReg2Button.setEnabled(false);
        this.exeBoard2Button.setEnabled(true);
    }//GEN-LAST:event_exeReg2ButtonActionPerformed

    private void exeBoard2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeBoard2ButtonActionPerformed
        rv.addRobotMove(robots[0], 1, Direction.W, Rotation.NO);
        rv.addRobotMove(robots[2], 1, Direction.E, Rotation.NO);
        rv.addRobotMove(robots[3], 1, Direction.N, Rotation.CCW90);
        rv.addPause(1000);
        rv.addRobotMove(robots[0], 1, Direction.W, Rotation.NO);
        rv.play();
        this.exeBoard2Button.setEnabled(false);
        this.shoot2Button.setEnabled(true);
    }//GEN-LAST:event_exeBoard2ButtonActionPerformed

    private void shoot2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoot2ButtonActionPerformed
        rv.addLaserFire(robots[0], Direction.E, 3, 15, false, false);
        rv.addPause(500);
        rv.addLaserFire(robots[1], Direction.S, 6, 9, true, false);
        rv.addRobotHit(robots[3], Direction.N);
        rv.addPause(500);
        rv.addLaserFire(robots[2], Direction.N, 3, 0, false, true);
        rv.addPause(500);
        rv.addLaserFire(robots[3], Direction.E, 1, 3, false, true);
        rv.addPause(1000);
        rv.addHideLaser();
        rv.play();
        this.shootButton.setEnabled(false);
    }//GEN-LAST:event_shoot2ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GameTestFrame gtf = new GameTestFrame();
                gtf.setVisible(true);
                gtf.setExtendedState(gtf.getExtendedState() | JFrame.MAXIMIZED_BOTH);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blueCardLabel;
    private javax.swing.JLabel blueCardNameLabel;
    private javax.swing.JPanel blueCardPanel;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JLabel bluePriorityLabel;
    private javax.swing.JLabel emeraldCardLabel;
    private javax.swing.JLabel emeraldCardNameLabel;
    private javax.swing.JPanel emeraldCardPanel;
    private javax.swing.JPanel emeraldPanel;
    private javax.swing.JLabel emeraldPriorityLabel;
    private javax.swing.JButton exeBoard2Button;
    private javax.swing.JButton exeBoardButton;
    private javax.swing.JButton exeReg2Button;
    private javax.swing.JButton exeRegButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loadReg2Button;
    private javax.swing.JButton loadRegButton;
    private javax.swing.JLabel redCardLabel;
    private javax.swing.JLabel redCardNameLabel;
    private javax.swing.JPanel redCardPanel;
    private javax.swing.JPanel redPanel;
    private javax.swing.JLabel redPriorityLabel;
    private javax.swing.JButton setup1Button;
    private javax.swing.JButton shoot2Button;
    private javax.swing.JButton shootButton;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JLabel yellowCardLabel;
    private javax.swing.JLabel yellowCardNameLabel;
    private javax.swing.JPanel yellowCardPanel;
    private javax.swing.JPanel yellowPanel;
    private javax.swing.JLabel yellowPriorityLabel;
    // End of variables declaration//GEN-END:variables
}
